version: '3.8'

services:
  quizicle_web:
    build: .
    restart: unless-stopped
    ports:
      - "8000"
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
      - static_volume:/app/staticfiles
    networks:
      - django_net

volumes:
  static_volume:

networks:
  django_net:
    driver: bridge