# Generated by Django 5.1.5 on 2025-04-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectname', '0005_rename_description_question_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='Correct',
            new_name='correct',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='Question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='Quiz',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='Result',
            new_name='result',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='User',
            new_name='user',
        ),
    ]
