# Generated by Django 5.1.5 on 2025-05-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectname', '0007_quiz_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='Complete the quiz—get results'),
        ),
    ]
