<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-03-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectname', '0002_alter_answer_question_alter_question_quiz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='QuizName',
            new_name='quiz_name',
        ),
    ]
=======
# Generated by Django 5.1.5 on 2025-03-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectname', '0002_alter_answer_question_alter_question_quiz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='QuizName',
            new_name='quiz_name',
        ),
    ]
>>>>>>> 1aa76192b204e63c9c4fe886ce418540db6ba48e
