# Generated by Django 5.1.5 on 2025-03-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectname', '0003_rename_quizname_quiz_quiz_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='QuestionCount',
            new_name='question_count',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='QuizMaximumPoints',
            new_name='quiz_maximum_points',
        ),
    ]
