# Generated by Django 5.1.5 on 2025-03-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectname', '0005_rename_description_question_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='creator',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
