# Generated by Django 5.1.5 on 2025-04-02 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectname', '0008_remove_question_creator_quiz_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='Correct',
            new_name='correct',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='Question',
            new_name='question',
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('result', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='projectname.quiz')),
            ],
        ),
        migrations.DeleteModel(
            name='Results',
        ),
    ]
