# Generated by Django 5.1.5 on 2025-05-17 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectname', '0011_alter_quiz_options_description_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='explanation',
            new_name='text',
        ),
        migrations.AddField(
            model_name='description',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='description_images/'),
        ),
        migrations.AlterField(
            model_name='description',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_description', to='projectname.question'),
        ),
    ]
