# Generated by Django 5.1.5 on 2025-05-23 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectname", "0014_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizResultAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectname.answer",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectname.question",
                    ),
                ),
                (
                    "quiz_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_result_answers",
                        to="projectname.results",
                    ),
                ),
            ],
        ),
    ]
